/*
 * SPDX-FileCopyrightText: 2024-2025 Pagefault Games
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 */

//! DO NOT EDIT THIS FILE - CREATED BY THE `eggMoves:parse` script automatically
import { MoveId } from "#enums/move-id";
import { SpeciesId } from "#enums/species-id";
import { TeamMemberId } from "#enums/team-member-id";

/**
 * An object mapping all base form {@linkcode SpeciesId}s to an array of {@linkcode MoveId}s corresponding
 * to their current egg moves.
 * Generated by the `eggMoves:parse` script using a CSV sourced from the current Balance Team spreadsheet.
 */
export const teamMemberMoveOptions = {
  [TeamMemberId.VM_VAPOREON]: [
    MoveId.GIGA_DRAIN,
    MoveId.GUNK_SHOT,
    MoveId.EARTH_POWER,
    MoveId.SAPPY_SEED,
    MoveId.DRAGON_DANCE,
    MoveId.AEROBLAST,
    MoveId.EARTH_POWER,
    MoveId.BITTER_BLADE,
  ],
  [TeamMemberId.VM_MAWILE]: [
    MoveId.DRAGON_DANCE,
    MoveId.AEROBLAST,
    MoveId.EARTH_POWER,
    MoveId.BITTER_BLADE,
    MoveId.DRAGON_DANCE,
    MoveId.AEROBLAST,
    MoveId.EARTH_POWER,
    MoveId.BITTER_BLADE,
  ],
  [TeamMemberId.ES_ESPEON]: [
    MoveId.AURA_SPHERE,
    MoveId.ARMOR_CANNON,
    MoveId.SHORE_UP,
    MoveId.ORIGIN_PULSE,
    MoveId.DRAGON_DANCE,
    MoveId.AEROBLAST,
    MoveId.EARTH_POWER,
    MoveId.BITTER_BLADE,
  ],
  [TeamMemberId.ES_SPIDOPS]: [
    MoveId.SANDSEAR_STORM,
    MoveId.SILK_TRAP,
    MoveId.TWIN_BEAM,
    MoveId.BLEAKWIND_STORM,
    MoveId.DRAGON_DANCE,
    MoveId.AEROBLAST,
    MoveId.EARTH_POWER,
    MoveId.BITTER_BLADE,
  ],
  [TeamMemberId.DS_DIA]: [
    MoveId.CLOSE_COMBAT,
    MoveId.NOXIOUS_TORQUE,
    MoveId.ATTACK_ORDER,
    MoveId.VICTORY_DANCE,
    MoveId.DRAGON_DANCE,
    MoveId.AEROBLAST,
    MoveId.EARTH_POWER,
    MoveId.BITTER_BLADE,
  ],
  [TeamMemberId.DS_SILVER]: [
    MoveId.BLEAKWIND_STORM,
    MoveId.FOCUS_BLAST,
    MoveId.CALM_MIND,
    MoveId.BOOMBURST,
    MoveId.DRAGON_DANCE,
    MoveId.AEROBLAST,
    MoveId.EARTH_POWER,
    MoveId.BITTER_BLADE,
  ],
} as const satisfies Record<TeamMemberId, [MoveId, MoveId, MoveId, MoveId, MoveId, MoveId, MoveId, MoveId]>;
